package org.example.bot.entity;

public enum State {
    CATEGORY,
    ADMIN_PANEL,
    ADD_CATEGORY,
    ADD_VIDEO,
    CHOOSE_CATEGORY,
    CHECK_NAME,
    CHECK_PASSWORD,
    ADD_PASSWORD,
    SEND_CONTACT, ADD_VIDEO_OR_MENU, CHOOSE_EDITING_CATEGORY, SAVE_CATEGORY, VIDEO_RENAMING, CHOOSE_VIDEO_FOR_RENAME, INPUT_NEW_VIDEO_TITLE, TOPIC
}